---
#  __  __            _       ____  ____   __      _       __     ___            _        
# |  \/  | __ _ _ __(_) __ _|  _ \| __ ) / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |\/| |/ _` | '__| |/ _` | | | |  _ \| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |  | | (_| | |  | | (_| | |_| | |_) | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|  |_|\__,_|_|  |_|\__,_|____/|____/| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                        \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | RedHat | MariaDB should be installed
      yum:
        name:  "mariadb"
        state: "present"

    - name: install-pkg | RedHat | MariaDB related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "mariadb-bench"
        - "mariadb-devel"
        - "mariadb-libs"
        - "mariadb-server"

    - name: install-pkg | RedHat | MySQL related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "mytop"
        - "mysqltuner"
  when: ansible_os_family == "RedHat"

