---
#  __  __            _       ____  ____   __      _       __     ___            _        
# |  \/  | __ _ _ __(_) __ _|  _ \| __ ) / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |\/| |/ _` | '__| |/ _` | | | |  _ \| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |  | | (_| | |  | | (_| | |_| | |_) | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|  |_|\__,_|_|  |_|\__,_|____/|____/| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                        \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | RedHat | MariaDB should be installed
      yum:
        state: "present"
        name:
          - "mariadb"
          - "mariadb-bench"
          - "mariadb-devel"
          - "mariadb-libs"
          - "mariadb-server"

    - name: install-pkg | RedHat | MySQL related packages should be installed
      yum:
        state: "present"
        name:
          - "innotop"
          - "mysqltuner"
          - "MySQL-python"
  when: ansible_os_family == "RedHat"

- block:
    - name: install-pkg | Debian | MariaDB should be installed
      apt:
        state: "present"
        name:
          - "libmariadb-dev"
          - "libmariadbclient-dev"
          - "libmariadb2"
          - "mariadb-client"
          - "mariadb-server"
          - "mariadb-test"

    - name: install-pkg | Debian | MySQL related packages should be installed
      apt:
        state: "present"
        name:
          - "mysqltuner"
          - "python-mysqldb"
  when: ansible_os_family == "Debian"

