---
#  __  __            _       ____  ____   __      _       __     ___            _        
# |  \/  | __ _ _ __(_) __ _|  _ \| __ ) / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |\/| |/ _` | '__| |/ _` | | | |  _ \| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |  | | (_| | |  | | (_| | |_| | |_) | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|  |_|\__,_|_|  |_|\__,_|____/|____/| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                        \_\_|        |___/_/                            
# make-config
- name: make-config | Calculation(innodb_buffer_pool_size)
  register: innodb_buffer_pool_size
  changed_when: innodb_buffer_pool_size.rc > 0
  command: >
    perl -le 'print int {{ ansible_memtotal_mb }} * 0.60 * {{ mariadb.memorysize }}'

- name: make-config | Calculation(innodb_log_file_size)
  register: innodb_log_file_size
  changed_when: innodb_log_file_size.rc > 0
  command: >
    perl -le 'print int {{ innodb_buffer_pool_size.stdout }} * 0.20 * {{ mariadb.memorysize }}'

- name: make-config | Calculation(thread_concurrency)
  register: thread_concurrency
  changed_when: thread_concurrency.rc > 0
  command: >
    perl -le 'print int {{ ansible_processor_vcpus }} * 2 * {{ mariadb.memorysize }}'

- name: make-config | Deploy /etc/my.cnf
  notify: Restart MariaDB
  template:
    src:    "etc/my.cnf.j2"
    dest:   "/etc/my.cnf"
    mode:   "0644"
    backup: "yes"

- name: make-config | Deploy each config file in /etc/my.cnf.d
  notify: Restart MariaDB
  template:
    src:  "{{ item }}"
    dest: "{{ mariadb.configroot }}/{{ item | basename | replace('.j2', '') }}"
    mode: "0644"
  with_fileglob: "templates{{ mariadb.configroot }}/*.cnf.j2"

- name: make-config | Deploy /etc/loglotate.d/mariadb
  template:
    src:  "etc/logrotate.d/mariadb.j2"
    dest: "/etc/logrotate.d/mariadb"
    mode: "0644"

- block:
    - name: make-config | MariaDB should be started for the first mysqladmin
      register: the_first_start
      service:
        name:  "mariadb"
        state: "started"

    - name: make-config | root password for localhost should be set
      when: the_first_start is changed
      register: mariadb_root_password
      mysql_user:
        name:        "root"
        host:        "localhost"
        password:    "{{ mariadb.rootpasswd }}"
        config_file: "/root/.my.cnf"

    - name: make-config | Deploy /root/.my.cnf
      when: mariadb_root_password is changed
      template:
        src:   "root/.my.cnf.j2"
        dest:  "/root/.my.cnf"
        mode:  "0600"
        owner: "root"
        group: "root"

    - name: make-config | root password for other hosts should be set
      when: mariadb_root_password is changed
      mysql_user:
        name:           "root"
        host:           "{{ item }}"
        password:       "{{ mariadb.rootpasswd }}"
        config_file:    "/root/.my.cnf"
        login_user:     "root"
        login_password: "{{ mariadb.rootpasswd }}"
      with_items:
        - "127.0.0.1"
  when: mariadb.rootpasswd is defined and mariadb.rootpasswd

