---
#  __  __            _       ____  ____   __      _       __     ___            _        
# |  \/  | __ _ _ __(_) __ _|  _ \| __ ) / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |\/| |/ _` | '__| |/ _` | | | |  _ \| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |  | | (_| | |  | | (_| | |_| | |_) | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|  |_|\__,_|_|  |_|\__,_|____/|____/| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                        \_\_|        |___/_/                            
# port-config
- name: port-config | 3306 port should not be opened
  firewalld:
    service:   "3306/tcp"
    state:     "disabled"
    immediate: true
    permanent: true

